Repository stolostron/multicluster-global-hub-operator-bundle, pull requests merged in 2025-08, with the labels that each got.

#196 update manager rbac
  bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
Labels: lgtm

#202 Setup konflux
  .tekton/images_digest_mirror_set.yaml
  .tekton/multicluster-global-hub-operator-bundle-globalhub-1-3-pull-request.yaml
  .tekton/multicluster-global-hub-operator-bundle-globalhub-1-3-push.yaml
  .tekton/multicluster-global-hub-operator-bundle-globalhub-1-5-pull-request.yaml
  .tekton/multicluster-global-hub-operator-bundle-globalhub-1-5-push.yaml
  Containerfile.bundle
  bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
  bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
  bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubagents.yaml
  bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
  bundle/metadata/annotations.yaml
  konflux-patch.sh
Labels: lgtm, approved

#223 add supportconfig in migration
  bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
Labels: lgtm, approved

#236 add migration config in csv
  bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
Labels: lgtm

#240 Update bundle to add placementRef
  bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
  bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#257 Update nudge
  .tekton/multicluster-global-hub-operator-bundle-globalhub-1-6-push.yaml
Labels: approved

#273 replace pipelineSpec with pipelineRef
  .tekton/multicluster-global-hub-operator-bundle-globalhub-1-5-pull-request.yaml
  .tekton/multicluster-global-hub-operator-bundle-globalhub-1-5-push.yaml
Labels: approved

#274 replace pipelineSpec with pipelineRef
  .tekton/multicluster-global-hub-operator-bundle-globalhub-1-4-pull-request.yaml
  .tekton/multicluster-global-hub-operator-bundle-globalhub-1-4-push.yaml
Labels: approved
